// <auto-generated />
using System;
using System.Collections.Generic;
using GradiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gradiapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradiApi.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<bool>("CurrentlyHere")
                        .HasColumnType("boolean")
                        .HasColumnName("currently_here");

                    b.Property<int>("FromYear")
                        .HasColumnType("integer")
                        .HasColumnName("from_year");

                    b.Property<int>("PersonalId")
                        .HasColumnType("integer")
                        .HasColumnName("personal_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("ToYear")
                        .HasColumnType("integer")
                        .HasColumnName("to_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_experiences");

                    b.HasIndex("PersonalId")
                        .HasDatabaseName("ix_experiences_personal_id");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("GradiApi.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int>("ExperienceId")
                        .HasColumnType("integer")
                        .HasColumnName("experience_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.PrimitiveCollection<List<string>>("Hobbies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("hobbies");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.PrimitiveCollection<List<string>>("ProgrammingLanguages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("programming_languages");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.PrimitiveCollection<List<string>>("TechStack")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tech_stack");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_personal");

                    b.ToTable("personal", (string)null);
                });

            modelBuilder.Entity("GradiApi.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GitHub")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("git_hub");

                    b.Property<string>("LiveDemo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("live_demo");

                    b.Property<int>("PersonalId")
                        .HasColumnType("integer")
                        .HasColumnName("personal_id");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.PrimitiveCollection<List<string>>("Tools")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tools");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("PersonalId")
                        .HasDatabaseName("ix_projects_personal_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("GradiApi.Models.Experience", b =>
                {
                    b.HasOne("GradiApi.Models.Personal", "Personal")
                        .WithMany("Experiences")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_experiences_personal_personal_id");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GradiApi.Models.Personal", b =>
                {
                    b.OwnsMany("GradiApi.Utils.Socials", "Socials", b1 =>
                        {
                            b1.Property<int>("PersonalId")
                                .HasColumnType("integer")
                                .HasColumnName("personal_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Link")
                                .HasColumnType("text")
                                .HasColumnName("link");

                            b1.Property<string>("Platform")
                                .HasColumnType("text")
                                .HasColumnName("platform");

                            b1.HasKey("PersonalId", "Id")
                                .HasName("pk_socials");

                            b1.ToTable("socials", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PersonalId")
                                .HasConstraintName("fk_socials_personal_personal_id");
                        });

                    b.Navigation("Socials");
                });

            modelBuilder.Entity("GradiApi.Models.Project", b =>
                {
                    b.HasOne("GradiApi.Models.Personal", "Personal")
                        .WithMany("Projects")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_personal_personal_id");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("GradiApi.Models.Personal", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
